Add kaiju field
genomic-medicine-sweden/gmsmetapost pull request #11
Opened 2022-06-29 14:51 UTC by ljmesi

Closes #10

2022-06-29 14:58 UTC, sofstam requested changes
Looks good to me. Just a minor change before approving.

2022-06-29 14:58 UTC, sofstam commented on subworkflows/local/input_check.nf
> +        exit 1, "ERROR: Please check input samplesheet -> kaiju classification file does not exist!\n${row.centrifuge}"
`row.kaiju` instead of `row.centrifuge`

2022-06-29 16:21 UTC, ljmesi commented on subworkflows/local/input_check.nf
> +        exit 1, "ERROR: Please check input samplesheet -> kaiju classification file does not exist!\n${row.centrifuge}"
Good catch! It's fixed now.

2022-06-30 07:32 UTC, sofstam approved these changes

2022-06-30 09:29 UTC, merged